version: '2'
services:

    #Testing the docs in
    #https://github.com/containous/traefik/blob/master/docs/user-guide/kv-config.md

    devops-consul-main:
        image: consul:v0.7.0
        ports:
            - "8400:8400"    
            - "8500:8500"    
            - "8053:53/udp"    
        networks:
            - proxy-test
        env_file: 
            - .env
            - .env.local
        labels:
            - "traefik.backend=consul-web"
            - "traefik.frontend.rule=Host:consul-web.$DOCKER_DC.$DOCKER_BASEDOMAIN,consul-web.docker"
            - "traefik.port=8500"
            - "traefik.frontend.entryPoints=http,https"
            - "traefik.enable=true"

    devops-git2consul-main:
        image: gavinjonespf/docker-git2consul:latest
        links:
            - devops-consul-main
        networks:
            - proxy-test
        env_file: 
            - .env
            - .env.local
        environment: 
            - CONSUL_ENDPOINT=devops-consul-main
            - CONSUL_PORT=8500
            - GIT_REPO=${CONSUL_GIT_REPO}
            - NAMESPACE=${TRAEFIK_NAMESPACE}
            - CFG=$CFG
        labels:
            - "traefik.enable=false"

    selfsign-ssl:
        image: prologic/mksslcrt
        entrypoint: /usr/bin/mksslcert /ssl/traefik.key /ssl/traefik.crt *.services.consul
        restart: never
        volumes:
            - proxy-ssl:/ssl/
        labels:
            - "traefik.enable=false"

#
#            --consulCatalog --consulCatalog.endpoint="devops-consul-main:8500" --consulCatalog.watch=true --consulCatalog.domain="$DOCKER_DC.$DOCKER_BASEDOMAIN" \
    proxy:
        image: ${TRAEFIK_IMAGE}:${TRAEFIK_TAG_VERSION}
        command: -d \
            --web --web.address=":8080" --web.readonly=true \
            --entryPoints='Name:http Address::80' --entryPoints='Name:https Address::443 TLS:/etc/traefik/customssl/traefik.crt,/etc/traefik/customssl/traefik.key' \
            --consul --consul.endpoint="devops-consul-main:8500" --consul.watch=true --consul.prefix=${TRAEFIK_NAMESPACE} \
            --docker --docker.endpoint="unix:///var/run/docker.sock" --docker.watch=true --docker.domain=$DOCKER_DC.$DOCKER_BASEDOMAIN --docker.exposedbydefault=false 
        ports:
            - "80:80"
            - "443:443"
            - "8080:8080"
        env_file: 
            - .env
            - .env.local
        labels:
            - "traefik.backend=proxy"
            - "traefik.frontend.rule=Host:traefik.$DOCKER_DC.$DOCKER_BASEDOMAIN,traefik.docker"
            - "traefik.port=8080"
            - "traefik.frontend.entryPoints=http,https"
            - "traefik.enable=true"
            - "traefik.docker.network=proxy-test"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - proxy-acme-data:/etc/traefik/acme/
            - proxy-ssl:/etc/traefik/customssl/
            - /dev/null:/etc/traefik/traefik.toml
        links:
            - devops-consul-main
        networks:
           - proxy-test

    #These will be set up in KV configs...
    whoami1:
        image: emilevauge/whoami
        networks:
            - proxy-test

    whoami2:
        image: emilevauge/whoami
        networks:
            - proxy-test

    whoami3:
        image: emilevauge/whoami
        networks:
            - proxy-test

    whoami4:
        image: emilevauge/whoami
        networks:
            - proxy-test

volumes:
  proxy-acme-data: {}
  proxy-ssl: {}

networks:
  proxy-test: {}
